'use client';

type IconName = 'bell' | 'search' | 'play' | 'file' | 'bookmark' | 'chart' | 'clock' | 'user' | 'chevron' | 'eye' | 'grid' | 'target' | 'accessibility' | 'external';

const iconPaths: Record<IconName, string> = {
  bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',
  search: 'm21 21-4.35-4.35M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15Z',
  play: 'M8 5v14l11-7-11-7Z',
  file: 'M6 3h9l3 3v15H6V3Zm9 0v4h3M9 12h6M9 16h6',
  bookmark: 'M6 3h12v18l-6-4-6 4V3Z',
  chart: 'M5 19V9M12 19V5M19 19v-7',
  clock: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0-14v5l3 2',
  user: 'M20 21a8 8 0 0 0-16 0M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',
  chevron: 'm9 18 6-6-6-6',
  eye: 'M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Zm10 3a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',
  grid: 'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z',
  target: 'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-4a6 6 0 1 0 0-12 6 6 0 0 0 0 12Zm0-4a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z',
  accessibility: 'M12 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm-6 3h12M12 8v13m-5 0 5-7 5 7',
  external: 'M14 5h5v5M19 5l-8 8M17 13v6H5V7h6',
};

function Icon({ name, filled = false }: { name: IconName; filled?: boolean }) {
  return <svg aria-hidden="true" className="h-5 w-5" fill={filled ? 'currentColor' : 'none'} viewBox="0 0 24 24" stroke="currentColor" strokeWidth={filled ? 0 : 1.7}><path d={iconPaths[name]} strokeLinecap="round" strokeLinejoin="round" /></svg>;
}
function SectionTitle({ number, title }: { number: string; title: string }) { return <div className="mb-5 flex items-center gap-3"><span className="text-[10px] font-bold text-primary-500">{number}</span><h2 className="text-[11px] font-bold tracking-[0.18em] text-neutral-900">{title}</h2></div>; }
function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`border-b border-neutral-200 p-4 md:p-5 ${className}`}>{children}</section>; }
function Dot() { return <span className="mx-1 text-primary-500">&bull;</span>; }

const primary = [['Primary 500', '#F97316'], ['Primary 400', '#FB923C'], ['Primary 300', '#FDBA74'], ['Primary 200', '#FED7AA'], ['Primary 100', '#FFEEE5']];
const neutral = [['Neutral 900', '#0F172A'], ['Neutral 700', '#334155'], ['Neutral 500', '#647488'], ['Neutral 300', '#CBD5E1'], ['Neutral 200', '#E2E8F0'], ['Neutral 100', '#F1F5F9'], ['Neutral 50', '#FAFAFC'], ['White', '#FFFFFF']];

export default function DesignPage() {
  return <main className="min-h-screen bg-[#f8f7f5] p-3 text-neutral-900 md:p-4" style={{ fontFamily: 'Inter, sans-serif' }}><div className="mx-auto max-w-[1500px] overflow-hidden rounded-lg border border-neutral-200 bg-white shadow-sm">
    <div className="grid md:grid-cols-[31%_69%]"><header className="border-b border-neutral-200 p-7 md:border-r md:p-10 lg:p-12"><div className="mb-12 flex items-center gap-3"><span className="text-3xl font-bold leading-none text-primary-500">V</span><span className="text-xl font-bold">Vertex</span></div><h1 className="mb-5 text-5xl leading-none text-neutral-900 md:text-6xl" style={{ fontFamily: '"Playfair Display", Georgia, serif' }}>Design System</h1><p className="max-w-sm text-sm leading-6 text-neutral-500">A unified design language for Vertex learning platform. Clean, modern and focused on clarity, consistency and intuitive learning experiences.</p><p className="mt-12 text-[10px] font-medium tracking-[0.12em] text-neutral-500">VERSION 1.0 <span className="mx-2 text-primary-500">|</span> MAY 2025</p></header><Panel className="border-b md:p-6 lg:p-8"><SectionTitle number="01" title="COLORS" /><div className="space-y-5"><ColorRow label="Primary" colors={primary} /><ColorRow label="Neutral" colors={neutral} /></div></Panel></div>
    <div className="grid md:grid-cols-2"><Panel className="md:border-r"><SectionTitle number="02" title="TYPOGRAPHY" /><div className="grid grid-cols-[105px_1fr] items-center gap-y-7"><div className="text-5xl" style={{ fontFamily: '"Playfair Display", Georgia, serif' }}>Ag</div><div><p className="text-base font-medium">Playfair Display</p><p className="mt-2 text-xs text-neutral-500">Elegant <Dot /> Readable <Dot /> Timeless</p></div><div className="text-5xl tracking-tight">Ag</div><div><p className="text-base font-medium">Inter</p><p className="mt-2 text-xs text-neutral-500">Clean <Dot /> Modern <Dot /> Highly legible</p></div></div></Panel><Panel><SectionTitle number="03" title="TYPE SCALE" /><div className="grid grid-cols-[1.2fr_1.5fr_1.2fr_1fr_1.3fr] gap-x-2 text-[10px] leading-6 text-neutral-500"><b className="font-medium text-neutral-700">Style</b><b className="font-medium text-neutral-700">Font</b><b className="font-medium text-neutral-700">Size / Line Height</b><b className="font-medium text-neutral-700">Weight</b><b className="font-medium text-neutral-700">Use</b>{[['Display 1','Playfair Display','48 / 56','Bold','Page titles'],['Display 2','Playfair Display','36 / 44','Bold','Section titles'],['Heading 1','Inter','28 / 36','Semi Bold','Card titles'],['Heading 2','Inter','22 / 30','Semi Bold','Sub section'],['Heading 3','Inter','18 / 26','Medium','Small titles'],['Body Large','Inter','16 / 24','Regular','Body copy'],['Body','Inter','14 / 20','Regular','Supporting text'],['Small','Inter','12 / 16','Regular','Captions, meta']].map(row => row.map((item, i) => <span key={`${row[0]}-${i}`} className={i === 0 ? 'text-neutral-900' : ''}>{item}</span>))}</div></Panel></div>
    <div className="grid md:grid-cols-[55%_45%]"><Panel className="md:border-r"><SectionTitle number="04" title="SPACING SYSTEM" /><p className="mb-7 text-[11px] font-medium">Base unit: 4px</p><div className="flex items-end justify-between gap-2">{[[4,'.25rem'],[8,'.5rem'],[12,'.75rem'],[16,'1rem'],[24,'1.5rem'],[32,'2rem'],[40,'2.5rem'],[48,'3rem'],[64,'4rem']].map(([size, rem]) => <div key={size} className="flex min-w-0 flex-1 flex-col items-center gap-2 text-[9px]"><div className="w-full max-w-9 rounded bg-primary-100" style={{ height: `${Number(size) + 8}px` }} /><b>{size}px</b><span className="text-neutral-500">({rem}rem)</span></div>)}</div></Panel><Panel><SectionTitle number="05" title="RADIUS & SHADOWS" /><p className="mb-3 text-[11px] font-medium">Radius</p><div className="mb-6 flex justify-between">{[['4px','xs'],['8px','sm'],['12px','md'],['16px','lg'],['24px','xl'],['Full','circle']].map(([label, sub]) => <div key={label} className="text-center text-[9px]"><div className={`mb-2 h-9 w-9 border border-neutral-200 ${sub === 'circle' ? 'rounded-full' : `rounded-${sub}`}`} /><b>{label}</b><p className="text-neutral-500">({sub})</p></div>)}</div><p className="mb-3 text-[11px] font-medium">Shadows</p><div className="grid grid-cols-4 gap-3">{[['Sm','0 1px 2px 0 rgba(15,23,42,.05)'],['Md','0 4px 12px -2px rgba(15,23,42,.08)'],['Lg','0 12px 24px -4px rgba(15,23,42,.12)'],['Xl','0 20px 40px -8px rgba(15,23,42,.16)']].map(([label, value]) => <div key={label} className="rounded bg-white p-3 shadow-md"><b className="text-[11px]">{label}</b><p className="mt-2 text-[8px] leading-3 text-neutral-500">{value}</p></div>)}</div></Panel></div>
    <div className="grid lg:grid-cols-[31%_45%_24%]"><Panel className="lg:border-r"><SectionTitle number="06" title="ICONS" /><p className="mb-3 text-[10px]">Outline Style</p><IconRow /><p className="mb-3 mt-6 text-[10px]">Filled Style</p><IconRow filled /><p className="mt-5 text-[10px] leading-5 text-neutral-500">Icon Specs<br />- 24x24px base size<br />- 2px stroke width (outline)<br />- Rounded line caps<br />- Consistent optical balance</p></Panel><Panel className="lg:border-r"><SectionTitle number="07" title="BUTTONS" /><div className="grid grid-cols-4 gap-3 text-[9px]"><div /><b>Primary</b><b>Secondary</b><b>Tertiary</b><b>Text</b>{['Default','Hover','Disabled'].map((state, row) => <div key={state} className="contents"><b className="self-center font-medium">{state}</b><Button label="Get Started" variant="primary" disabled={row === 2} /><Button label="Explore Courses" variant="secondary" disabled={row === 2} /><Button label="View Lesson" variant="tertiary" disabled={row === 2} /><Button label="Watch Video" variant="text" disabled={row === 2} /></div>)}</div><p className="mt-6 text-[10px] leading-5 text-neutral-500">Button Specs<br />- Height: 44px (default)<br />- Padding: 0 16px (lg), 0 12px (md)<br />- Radius: 12px<br />- Font: Inter Medium (14-16px)</p></Panel><Panel><SectionTitle number="08" title="INPUTS" /><p className="mb-2 text-[10px] font-medium">Search / Text Input</p><div className="mb-4 flex h-9 items-center gap-2 rounded border border-neutral-200 px-3 text-[10px] text-neutral-400"><Icon name="search" /><span className="flex-1">Search anything...</span><kbd className="rounded border px-1.5 py-0.5 text-[8px]">âŒ˜ K</kbd></div><p className="mb-2 text-[10px] font-medium">Select</p><div className="flex h-9 items-center justify-between rounded border border-neutral-200 px-3 text-[10px]">Most Relevant <Icon name="chevron" /></div><p className="mt-5 text-[10px] leading-5 text-neutral-500">Field Specs<br />- Height: 44px<br />- Radius: 12px<br />- Border: 1px solid #E2E8F0<br />- Padding: 0 16px<br />- Focus: Border color #FF7316</p></Panel></div>
    <div className="grid md:grid-cols-[31%_38%_31%]"><Panel className="md:border-r"><SectionTitle number="09" title="BADGES / TAGS" /><div className="grid grid-cols-3 gap-3 text-[10px]"><div>Video<div className="mt-3 inline-block rounded bg-primary-100 px-3 py-1 text-[9px] font-medium text-primary-500">VIDEO</div></div><div>Lesson<div className="mt-3 inline-block rounded bg-[#f1effd] px-3 py-1 text-[9px] font-medium text-[#5146a5]">LESSON</div></div><div>Popular<div className="mt-3 inline-block rounded bg-[#fff0e8] px-3 py-1 text-[9px] font-medium text-primary-500">POPULAR</div></div></div></Panel><Panel className="md:border-r"><SectionTitle number="10" title="STATUS / INDICATORS" /><div className="flex flex-wrap items-center gap-5 text-[10px]"><Status label="In Progress" type="progress" /><Status label="Completed" type="completed" /><Status label="Now Playing" type="playing" /><Status label="Locked" type="locked" /></div></Panel><Panel><SectionTitle number="11" title="PROGRESS BAR" /><div className="flex items-center gap-7 pt-3"><div className="h-1.5 flex-1 rounded-full bg-neutral-100"><div className="h-full w-3/5 rounded-full bg-primary-500" /></div><span className="whitespace-nowrap text-[10px]">35% complete</span></div></Panel></div>
    <Panel><SectionTitle number="12" title="CARDS" /><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><CourseCard /><VideoCard /><LessonCard /><ResourceCard /></div></Panel>
    <div className="grid md:grid-cols-[31%_69%]"><Panel className="md:border-r"><SectionTitle number="13" title="NAVIGATION" /><div className="flex items-center gap-5 text-[10px]"><span className="text-2xl font-bold text-primary-500">V</span><b>Vertex</b><span className="text-primary-500">Courses</span><span>My Learning</span></div><div className="mt-6 text-[10px] text-neutral-500">Breadcrumbs<br /><span className="leading-7">All Courses <Icon name="chevron" /> Next.js for Production <Icon name="chevron" /> Data Fetching &amp; Caching</span></div></Panel><Panel><div className="mb-7 mt-7 text-[10px] text-neutral-500">Pagination <span className="ml-10 rounded border border-primary-500 px-2 py-1 text-primary-500">1</span> <span className="ml-4">2</span> <span className="ml-4">3</span> <span className="ml-4">...</span> <span className="ml-4">8</span> <Icon name="chevron" /></div></Panel></div>
    <div className="grid gap-4 border-t border-neutral-200 p-4 md:grid-cols-4 md:p-5"><SectionTitle number="14" title="PRINCIPLES" />{[['eye','Clarity First','Every element should communicate clearly.'],['grid','Consistency','Use components and patterns consistently across the platform.'],['target','Focus & Calm','Remove noise and help learners focus on what matters.'],['accessibility','Accessible','Design with accessibility and inclusivity in mind.']].map(([icon, title, desc]) => <div key={title} className="flex gap-3"><Icon name={icon as IconName} /><div><b className="text-[10px]">{title}</b><p className="mt-1 text-[9px] leading-4 text-neutral-500">{desc}</p></div></div>)}</div>
  </div></main>;
}

function ColorRow({ label, colors }: { label: string; colors: string[][] }) { return <div><p className="mb-3 text-[11px] font-medium">{label}</p><div className="grid grid-cols-2 gap-3 md:grid-cols-5 lg:grid-cols-8">{colors.map(([name, hex]) => <div key={name}><div className="h-10 rounded border border-neutral-200" style={{ backgroundColor: hex }} /><p className="mt-2 text-[9px]">{name}</p><p className="text-[8px] text-neutral-500">{hex}</p></div>)}</div></div>; }
function IconRow({ filled = false }: { filled?: boolean }) { return <div className="flex flex-wrap gap-4">{(['bell','search','play','file','bookmark','chart','clock','user','chevron'] as IconName[]).map(name => <Icon key={name} name={name} filled={filled} />)}</div>; }
function Button({ label, variant, disabled }: { label: string; variant: 'primary' | 'secondary' | 'tertiary' | 'text'; disabled?: boolean }) { const styles = { primary: 'bg-primary-500 text-white', secondary: 'border border-primary-500 text-primary-500', tertiary: 'border border-neutral-200 text-neutral-900', text: 'text-primary-500' }; return <button disabled={disabled} className={`flex h-7 items-center justify-center gap-1 whitespace-nowrap rounded px-2 text-[8px] ${styles[variant]} ${disabled ? 'opacity-35' : ''}`}>{label}{variant === 'text' && <Icon name="play" />}</button>; }
function Status({ label, type }: { label: string; type: string }) { return <span className="flex items-center gap-1.5 whitespace-nowrap"><span className={`flex h-3.5 w-3.5 items-center justify-center rounded-full border ${type === 'completed' ? 'border-green-600 text-green-600' : type === 'playing' ? 'border-primary-500 bg-primary-500 text-white' : 'border-primary-500'}`}>{type === 'completed' ? 'âœ“' : type === 'playing' ? '>' : type === 'locked' ? <Icon name="bookmark" /> : ''}</span>{label}</span>; }
function CardShell({ children, label }: { children: React.ReactNode; label: string }) { return <div><p className="mb-2 text-[9px] text-neutral-600">{label}</p><div className="min-h-36 rounded-md border border-neutral-200 p-3">{children}</div></div>; }
function CourseCard() { return <CardShell label="Course Card"><div className="flex gap-2"><div className="flex h-7 w-7 items-center justify-center rounded bg-neutral-900 text-white">N</div><b className="text-[11px]">Next.js for Production</b></div><p className="mt-3 text-[9px] leading-4 text-neutral-500">Build scalable, high-performance web applications with Next.js.</p><p className="mt-7 flex items-center gap-1 text-[8px] text-neutral-500"><Icon name="chart" /> Intermediate <Icon name="clock" /> 18h 24m <Icon name="file" /> 12 modules</p></CardShell>; }
function VideoCard() { return <CardShell label="Lesson Card (Video)"><span className="rounded bg-primary-100 px-2 py-1 text-[8px] font-medium text-primary-500">VIDEO</span><b className="mt-3 block text-[10px]">Data Fetching in Server Components</b><p className="mt-2 text-[9px] leading-4 text-neutral-500">Learn how to fetch data on the server using async/await and best practices.</p><p className="mt-3 text-[8px] text-neutral-500">Lesson 5.1 <span className="mx-2">|</span> 12:45 <span className="float-right text-primary-500">Watch from 12:45</span></p></CardShell>; }
function LessonCard() { return <CardShell label="Lesson Card (Lesson)"><span className="rounded bg-[#f1effd] px-2 py-1 text-[8px] font-medium text-[#5146a5]">LESSON</span><b className="mt-3 block text-[10px]">Data Fetching &amp; Caching</b><p className="mt-2 text-[9px] leading-4 text-neutral-500">Explore different data fetching methods in Next.js and how to cache and revalidate data for optimal performance.</p><p className="mt-3 text-[8px] text-neutral-500">Module 5 <span className="float-right text-primary-500">View lesson</span></p></CardShell>; }
function ResourceCard() { return <CardShell label="Resource Card"><div className="flex gap-2"><Icon name="file" /><b className="text-[10px]">Caching and Revalidation Guide</b></div><p className="mt-3 text-[9px] leading-4 text-neutral-500">Deep dive into Next.js caching strategies.</p><p className="mt-7 text-[8px] text-neutral-500">PDF <span className="mx-2">|</span> 1.2 MB <span className="float-right text-primary-500"><Icon name="external" /></span></p></CardShell>; }
